---
# Tasks for roles
- name: Ensure dotfiles are present
  include_role:
    name: dotfiles

- name: Ensure utilities are installed
  package:
    name: "{{ item }}"
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  with_items:
   - screen
   - wget
   - vim
