---
# master playbook

- hosts: dev
  roles:
   - role: shell
   - role: mac-automount
   - role: mac-configuration
   - role: mac-desktop
   - role: mac-transmission
   - role: mac-dev-tools

- hosts: mediacenter
  roles:
   - role: shell
   - role: kodi
   - role: transmission

- hosts: vpn
  roles:
   - role: shell
   - role: sshd
