---
# master playbook

- hosts: dev
  roles:
   - shell
   - mac-configuration
   - mac-desktop
   - mac-transmission
   - mac-dev-tools

- hosts: mediacenter
  roles:
   - shell
   - kodi

- hosts: vpn
  roles:
   - shell
   - sshd
