---
# master playbook
- hosts: debian
  gather_facts: False
  tasks:
    - name: Ensure DMI decode is present
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - dmidecode
        - python-pip
  roles:
    - debian-shell

- hosts: all
  roles:
    - sshd
    - shell

- hosts: mac
  roles:
    - mac-node

- hosts: dev
  roles:
    - mac-automount
    - mac-configuration
    - mac-desktop
    - mac-transmission
    - mac-dev-tools

- hosts: mediacenter
  roles:
    - kodi
    - transmission

- hosts: vpn
  roles: []
