---
# Tasks for roles

#- name: example
#  action: example
#  notify:
#    - restart service
#  tags:
#    - example

- name: Ensure repository is cloned
  git:
    repo: 'https://github.com/maxwo/dotfiles.git'
    dest: "{{ ansible_env.HOME }}/dotfiles"

- name: Ensure user directories exist
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: 0700
    recurse: yes
  with_items:
    - .vim/backups
    - .vim/swaps
    - .vim/undo
    - .gnupg

- name: Ensure vim plugins are installed
  git:
    repo: '{{ item.repository }}'
    dest: "{{ ansible_env.HOME }}/.vim/{{ item.name }}"
  with_items:
    - name: editorconfig-vim
      repository: https://github.com/editorconfig/editorconfig-vim.git

- name: Ensure SSH dotfiles symlinks are set with correct permissions
  file:
    src: "{{ ansible_env.HOME}}/dotfiles/ssh/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
    mode: 0600
    state: link
    force: yes
  with_items:
    - authorized_keys
    - config

- name: Ensure GPG dotfiles symlinks are set
  file:
    src: "{{ ansible_env.HOME}}/dotfiles/gnupg/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.gnupg/{{ item }}"
    state: link
    force: yes
  with_items:
    - gpg.conf
  tags:
    - dotfiles

- name: Ensure dotfiles standard symlinks are set
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - ansible.cfg
    - curlrc
    - editorconfig
    - gitconfig
    - screenrc
    - vimrc
    - wgetrc
    - zshrc
