---
# Tasks for roles

#- name: example
#  action: example
#  notify:
#    - restart service
#  tags:
#    - example

- name: Ensure applications are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
   - dropbox
   - firefox
   - flux
   - google-chrome
   - keepassx
   - transmission
   - vlc
