---
# Tasks for roles

#- name: example
#  action: example
#  notify:
#    - restart service
#  tags:
#    - example

- name: Ensure installed Homebrew packages are up to date
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
