---
# Tasks for roles

#- name: example
#  action: example
#  notify:
#    - restart service
#  tags:
#    - example

- name: Ensure ZSH is up to date
  apt:
    name: zsh
    state: latest
  become: yes
  become_method: su
