---
# Tasks for roles

#- name: example
#  action: example
#  notify:
#    - restart service
#  tags:
#    - example

- name: Ensure base packages are up to date
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  become: yes
  environment:
    PATH: /bin:/sbin:/usr/bin:/usr/sbin
  with_items:
   - zsh
   - git
