---
# Tasks for roles

- name: Ensure Homebrew packages are up to date
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  notify: Clean old Homebrew versions
  tags: packages, macosx, upgrade

- name: Ensure Homebrew casks are up to date
  homebrew_cask:
    upgrade_all: yes
  tags: packages, macosx, upgrade

- name: Ensure older versions are cleaned-up
  meta: flush_handlers
