---
# Tasks for roles

#- name: example
#  action: example
#  notify:
#    - restart service
#  tags:
#    - example

- name: Ensure PWM audio is set to 2
  lineinfile:
    path: /boot/config.txt
    line: audio_pwm_mode=2
    state: present
  become_method: sudo

- name: Ensure SMB credentials are available
  template:
    src: smbcredentials
    dest: "{{ ansible_env.HOME }}/.smbcredentials"
    owner: osmc
    group: root
    mode: "u=rw,g=r,o="

- name: Ensure network drives are automounted
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
    state: present
  become_method: sudo
  with_items:
    - //192.168.3.2/Media      /mnt/media      cifs    x-systemd.automount,noauto,uid=0,users,credentials=/home/osmc/.smbcredentials,sec=ntlmv2 0 0
    - //192.168.3.2/Downloads      /mnt/downloads      cifs    x-systemd.automount,noauto,uid=0,users,credentials=/home/osmc/.smbcredentials,sec=ntlmv2 0 0

- name: Ensure media sources are configured
  template:
    src: sources.xml
    dest: "{{ ansible_env.HOME }}/.kodi/userdata/sources.xml"
