---
# Tasks for roles

- name: Ensure gems are installed
  gem:
    name: "{{ item }}"
    state: latest
  environment:
    GEM_HOME: ~/.gem
    GEM_PATH: ~/.gem
  with_items:
   - travis
   - rhc

- name: Ensure Node is installed with NPM
  homebrew:
    name: node
    state: latest
    install_options: with-npm

- name: Ensure Homebrew packages are installed
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - awscli
    - dos2unix
    - gcc
    - git
    - golang
    - gom
    - gperftools
    - gpg
    - lnav
    - hg
    - kops
    - kubernetes-helm
    - maven
    - python3
    - yarn

- name: Ensure non-edge Docker is removed
  homebrew_cask:
    name: docker
    state: absent

- name: Ensure legacy dev applications are remove
  homebrew_cask:
    name: "{{ item }}"
    state: absent
  with_items:
    - sublime-text

- name: Ensure dev applications are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - atom
    - docker-edge
    - eclipse-java
    - firefoxnightly
    - google-chrome-canary
    - iterm2
    - java
    - oracle-jdk
    - postman
    - sourcetree
    - sublime-text
    - vagrant
    - virtualbox
    - visual-studio-code

- name: Ensure Lombok destination is created
  file:
    name: "{{ lombok_install_path }}"
    state: directory

- name: Ensure Lombok is downloaded
  get_url:
    url: "{{ lombok_url }}"
    dest: "{{ lombok_install_file }}"

- name: Ensure Lombok is declared in Eclipse installations
  lineinfile:
    path: "{{ item }}"
    insertafter: -vmargs
    line: -javaagent:{{ lombok_install_file }}
  with_fileglob:
    - "{{ eclipse_ini_paths }}"

- name: Ensure Javascript dev tools are globally installed
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
  with_items:
    - "@angular/cli"
    - bower
    - browser-sync
    - grunt-cli
    - gulp-cli
    - npm-check-updates
    - vue-cli
  tags: js

- name: Ensure Atom plugins are up to date
  include_role:
    name: jgkim.atom
  vars:
    atom_upgrade_all: true
    atom_packages:
      - asciidoc-preview
      - atom-beautify
      - atom-jinja2
      - atom-typescript
      - busy-signal
      - cssbeautify
      - docker
      - file-icons
      - go-plus
      - intentions
      - jade-beautify
      - language-ansible
      - language-asciidoc
      - language-awk
      - language-cpp14
      - language-docker
      - language-erlang
      - language-hcl
      - language-ignore
      - language-ini
      - language-groovy
      - language-jade
      - language-javascript-jsx
      - language-make
      - language-markdown
      - language-pug
      - language-sass
      - language-terraform
      - language-toml
      - language-vue
      - linter
      - linter-docker
      - linter-gcc
      - linter-eslint
      - linter-markdown
      - linter-sass-lint
      - linter-shellcheck
      - linter-terraform-syntax
      - linter-toml
      - linter-ui-default
      - minimap
      - minimap-find-and-replace
      - minimap-git-diff
      - minimap-pigments
