---
# tasks file for roles/mac-node
- name: Ensure node exporter is available
  homebrew:
    name: node_exporter
    state: present

- name: Ensure node exporter daemon is declared
  template:
    src: "{{ node_exporter_daemon_plist }}"
    dest: /Library/LaunchDaemons/{{ node_exporter_daemon_plist }}
    mode: 0644
  become: yes
  notify: Install daemon
